### PR TITLE
feat(esl-utility): event listener subscription logic fix and ability to inherit listener definition

### PR DESCRIPTION
**Pull request by ala-n**
In bounds of this PR:
1. Add a check to prevent an empty targets listener from subscription
2. Make able to inherit event listener method definition meta from superclass with a short version of `@listen` decorator
3. (cosmetic) `prop` decorator added to the `esl-mixin-element` and `esl-base-element` modules export
4. cover new functionality by tests

The following inheritance cases are available :
For now the following syntax is available:
```
class Super {
   @listen({...})
   onEvent() {}
}

// Unsubscribe option 
class ClassA {
   // overrides without listener definition
   onEvent() {}
}

// Replaces Super definition
class ClassB {
   @listen({...})
   onEvent() {}
}

// Inherit and merge Super event listener definition
class ClassC {
   @listen({inherit: true, ...})
   onEvent() {}
}

// Just inherit Super event listener definition
class ClassD {
   @listen({inherit: true})
   onEvent() {}
}

// Sort version to just inherit Super event listener definition
class ClassE {
   @listen()
   onEvent() {}
}
```

----

@exadel-inc/esl-all-contributors, please feel free to leave feedback about the current implementation.

Also, please take a look at the inheritance use cases described above, and please let me know:

1. Is this behavior looks safe and intuitive for you in general?
(Short emoji: 👍🏻(yes) / 👎🏻 (no) )
2. Do we need to have a short version to inherit listener metadata,
or we should restrict case of ClassE to the full version (ClassD)
(Short emoji: 🚀 (short version ok) / 😕 (short version confused) )

### CODE REVIEW

**Comment by ala-n** [comment]
@exadel-inc/esl-core-team, @exadel-inc/esl-all-contributors, please feel free to leave feedback about the current implementation.

Also, please take a look at the inheritance use cases described above, and please let me know:
1. Is this behavior looks safe and intuitive for you in general? 
(Short emoji: 👍🏻(yes) / 👎🏻 (no) )
2. Do we need to have a short version to inherit listener metadata, 
or we should restrict case of `ClassE` to the full version (`ClassD`)  
(Short emoji: 🚀 (short version ok) / 😕 (short version confused) )

**Review by dshovchko — APPROVED** [review]

**Comment by ala-n** [comment]
Due to votes for the short version `@listen()` were divided (2nd question to vote), 
I will split this discussion into the follow-up and remove that ability for the current implementation.

**Review by dshovchko — APPROVED** [review]

**Review by fshovchko — APPROVED** [review]

**Review by NastaLeo — APPROVED** [review]

**Review by yadamskaya — APPROVED** [review]

**Comment by ala-n** [comment]
Merge to include into nearest release

**Pull request merged**
