### PR TITLE
feat: github pages with eleventy

### PR DESCRIPTION
**Pull request by abarmina**
switching to nunjucks of the main page of the site (on development stage)

### CODE REVIEW

**Review by nattallius — APPROVED** [review]

**Review by ala-n — APPROVED** [review]
Looks superb! ❤️ 
To be honest, I totally glad that we chose 11ty as a basis and njk as a syntax. It looks much more structured and readable for our purposes.

**Review by YanaBr — APPROVED** [review]

**Review by PolinaVolchetskaya — APPROVED** [review]

**Review by andreybelous — APPROVED** [review]

**Comment by ala-n** [comment]
Ok, looks like github stalled on the checks, I'll try to kick it...

**Pull request merged**
