### PR TITLE
version updates, style-guide rework and editorconfig validation update

### PR DESCRIPTION
**Pull request by ala-n**
Also resolve #210

### CODE REVIEW

**Review by andreybelous — APPROVED** [review]

**Review by dshovchko — APPROVED** [review]

**Review by YanaBr — APPROVED** [review]

**Review by nattallius — APPROVED** [review]

**Review by abarmina — COMMENTED** [review]
It seems to me that you need to add lint:spaces to the pre-push

**Review by abarmina — APPROVED** [review]

**Comment by ala-n** [comment]
> It seems to me that you need to add lint:spaces to the pre-push

Thanks! updted.

**Review by YanaBr — APPROVED** [review]

**Review by julia-murashko — APPROVED** [review]

**Pull request merged**
