### PR TITLE
feat(esl-utils): update promisifyTimeout with extended syntax support

### PR DESCRIPTION
**Pull request by petemarianne**
Created extended version of `promisifyTimeout` method #858

### CODE REVIEW

**Comment by petemarianne** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Review by nattallius — APPROVED** [review]
Please, also correct the JSDoc to this function

**Comment by ala-n** [comment]
recheckcla

**Review by ala-n — APPROVED** [review]

**Comment by ala-n** [comment]
> **_I have read the CLA Document and I hereby sign the CLA_**

It seems to be the GitHub user that you used locally for commits is not connected to the GitHub account.

Please:
1) Check the local git user that you used to creat current commits. First of all email.
You can use the following command in the scope of the project
```bash
git config user.email
```
2) Make sure that the email you used locally connected to your GitHub user account
3) After Step 1 and 2 check that current CLA warning disappeared, re comment your agreement if the CLA bot still not added your to the allowed list.

**Comment by petemarianne** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Comment by petemarianne** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Comment by ala-n** [comment]
Cloaing due to moving to #868

**Pull request closed without merging**
