### PR TITLE
folder esl-alert

### PR DESCRIPTION
**Pull request by Onyinye91-ctrl**
# PR Details

I replace tense of verbs in esl-alert folder

## Related Issue

https://github.com/exadel-inc/esl/issues/521

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by Onyinye91-ctrl** [comment]
@abarmina i am through with esl-alert. Can you please check to see if i am on the right track?

**Comment by abarmina** [comment]
@Onyinye91-ctrl, I'm afraid not really.
for example, you changed the words `shows/hides`, `Defines` correctly. 
but you don't need to change nouns. only the verbs need to be changed. we say "this component is doing something", the component is the third person, so the verb must contain the ending `s`. in the description, we do not indicate the pronoun every time, but we decided to use the verb anyway in the third person

**Comment by Onyinye91-ctrl** [comment]
@abarmina Okay. I will fix that

**Comment by Onyinye91-ctrl** [comment]
@abarmina I made some changes to the file. Can you check if i am in line so that i can move to other files. Thanks

**Comment by Onyinye91-ctrl** [comment]
@abarmina Done

**Comment by Onyinye91-ctrl** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
